version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links: 
      - client
      - server
  client:
    build: ./client
    container_name: 90Box_client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: 90Box_server_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules